name: Notify Pushover on New Issue

on:
  issues:
    types: [opened]

jobs:
  pushover:
    runs-on: ubuntu-latest
    steps:
      - name: Send Pushover Notification
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          curl -s \
            --form-string "token=$PUSHOVER_API_TOKEN" \
            --form-string "user=$PUSHOVER_USER_KEY" \
            --form-string "title=New GitHub Issue" \
            --form-string "message=Issue: $ISSUE_TITLE" \
            --form-string "url=$ISSUE_URL" \
            https://api.pushover.net/1/messages.json
